'use strict';
var router = require('express').Router();
module.exports = router;

// Yahoo Stocks dummy data

router.get('/', function (req, res, next) {
  let data = {
  "response": {
    "status": "ok",
    "userTier": "developer",
    "total": 180824,
    "startIndex": 1,
    "pageSize": 100,
    "currentPage": 1,
    "pages": 1809,
    "orderBy": "relevance",
    "results": [
      {
        "id": "football/2016/aug/03/marta-brazils-brilliant-football-nomad",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-03T08:00:42Z",
        "webTitle": "Marta, Brazil's brilliant football nomad",
        "webUrl": "https://www.theguardian.com/football/2016/aug/03/marta-brazils-brilliant-football-nomad",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/03/marta-brazils-brilliant-football-nomad",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/may/07/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-05-07T19:00:55Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/may/07/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/may/07/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "global/football-league-blog/2016/apr/30/football-league-your-thoughts-sheffield-wednesday",
        "type": "article",
        "sectionId": "global",
        "sectionName": "Global",
        "webPublicationDate": "2016-04-30T19:25:35Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/global/football-league-blog/2016/apr/30/football-league-your-thoughts-sheffield-wednesday",
        "apiUrl": "https://content.guardianapis.com/global/football-league-blog/2016/apr/30/football-league-your-thoughts-sheffield-wednesday",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/apr/23/football-league-your-thoughts-brighton-wigan-york",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-23T17:21:36Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/apr/23/football-league-your-thoughts-brighton-wigan-york",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/apr/23/football-league-your-thoughts-brighton-wigan-york",
        "isHosted": false
      },
      {
        "id": "football/blog/2016/apr/16/football-league-your-thoughts-blog",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-16T18:50:28Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/blog/2016/apr/16/football-league-your-thoughts-blog",
        "apiUrl": "https://content.guardianapis.com/football/blog/2016/apr/16/football-league-your-thoughts-blog",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/apr/09/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-09T18:46:22Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/apr/09/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/apr/09/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/mar/28/football-league-blog-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-03-28T17:48:17Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/mar/28/football-league-blog-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/mar/28/football-league-blog-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/apr/02/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-02T16:48:20Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/apr/02/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/apr/02/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/mar/19/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-03-19T18:16:45Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/mar/19/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/mar/19/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/mar/13/football-league-your-thoughts-middlesbrough-karanka-burnley",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-03-13T01:17:30Z",
        "webTitle": "Football League: your thoughts | Simon Burnton",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/mar/13/football-league-your-thoughts-middlesbrough-karanka-burnley",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/mar/13/football-league-your-thoughts-middlesbrough-karanka-burnley",
        "isHosted": false
      },
      {
        "id": "football/2016/may/24/traditional-football-supporters-priced-out",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-05-24T18:35:00Z",
        "webTitle": "Traditional football supporters priced out | Letters",
        "webUrl": "https://www.theguardian.com/football/2016/may/24/traditional-football-supporters-priced-out",
        "apiUrl": "https://content.guardianapis.com/football/2016/may/24/traditional-football-supporters-priced-out",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/mar/05/football-league-your-thoughts-charlton-rotherham",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-03-05T20:11:31Z",
        "webTitle": "Football League: your thoughts | Niall McVeigh",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/mar/05/football-league-your-thoughts-charlton-rotherham",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/mar/05/football-league-your-thoughts-charlton-rotherham",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/feb/27/football-league-blog-your-thoughts-sanogo-middlesbrough-northampton",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-02-27T20:18:24Z",
        "webTitle": "Football League: your thoughts | Rob Bleaney",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/feb/27/football-league-blog-your-thoughts-sanogo-middlesbrough-northampton",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/feb/27/football-league-blog-your-thoughts-sanogo-middlesbrough-northampton",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/feb/20/football-league-your-thoughts-burnley-northampton",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-02-20T19:16:43Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/feb/20/football-league-your-thoughts-burnley-northampton",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/feb/20/football-league-your-thoughts-burnley-northampton",
        "isHosted": false
      },
      {
        "id": "football/2016/jan/10/jurgen-klopp-liverpool-pep-guardiola",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-10T22:49:00Z",
        "webTitle": "Jürgen Klopp warns Pep Guardiola: England is football, football, football",
        "webUrl": "https://www.theguardian.com/football/2016/jan/10/jurgen-klopp-liverpool-pep-guardiola",
        "apiUrl": "https://content.guardianapis.com/football/2016/jan/10/jurgen-klopp-liverpool-pep-guardiola",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/feb/13/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-02-13T19:17:13Z",
        "webTitle": "Football League: your thoughts | Les Roopanarine",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/feb/13/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/feb/13/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/feb/06/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-02-06T20:44:14Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/feb/06/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/feb/06/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/04/the-fiver-wales-euro-2016",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-04T14:53:35Z",
        "webTitle": "The Fiver | Wales is the home of football",
        "webUrl": "https://www.theguardian.com/football/2016/jul/04/the-fiver-wales-euro-2016",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/04/the-fiver-wales-euro-2016",
        "isHosted": false
      },
      {
        "id": "sport/blog/2016/jul/08/the-joy-of-six-terrible-penalties",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-08T10:46:58Z",
        "webTitle": "The Joy of Six: terrible football penalties",
        "webUrl": "https://www.theguardian.com/sport/blog/2016/jul/08/the-joy-of-six-terrible-penalties",
        "apiUrl": "https://content.guardianapis.com/sport/blog/2016/jul/08/the-joy-of-six-terrible-penalties",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/jan/23/football-league-your-thoughts-hull-middlesbrough",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-23T19:37:01Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/jan/23/football-league-your-thoughts-hull-middlesbrough",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/jan/23/football-league-your-thoughts-hull-middlesbrough",
        "isHosted": false
      },
      {
        "id": "football/2016/jan/30/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-30T19:31:08Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/2016/jan/30/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/2016/jan/30/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "music/2016/jun/23/dont-deny-the-welsh-their-football-glory",
        "type": "article",
        "sectionId": "music",
        "sectionName": "Music",
        "webPublicationDate": "2016-06-23T17:50:05Z",
        "webTitle": "Don’t deny the Welsh their football glory | Letters",
        "webUrl": "https://www.theguardian.com/music/2016/jun/23/dont-deny-the-welsh-their-football-glory",
        "apiUrl": "https://content.guardianapis.com/music/2016/jun/23/dont-deny-the-welsh-their-football-glory",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/17/football-transfer-rumours-robert-lewandowski-liverpool-julian-draxler-manchester-united",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-17T08:21:26Z",
        "webTitle": "Football transfer rumours: Robert Lewandowski to Liverpool?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/17/football-transfer-rumours-robert-lewandowski-liverpool-julian-draxler-manchester-united",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/17/football-transfer-rumours-robert-lewandowski-liverpool-julian-draxler-manchester-united",
        "isHosted": false
      },
      {
        "id": "football/2016/jan/16/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-16T18:38:48Z",
        "webTitle": "Football League: your thoughts | Les Roopanarine",
        "webUrl": "https://www.theguardian.com/football/2016/jan/16/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/2016/jan/16/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2016/jan/02/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-02T18:07:39Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2016/jan/02/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2016/jan/02/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/dec/28/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-12-28T17:48:12Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/dec/28/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/dec/28/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "politics/2016/may/27/vote-leave-launches-50m-football-prediction-competition-euro-2016",
        "type": "article",
        "sectionId": "politics",
        "sectionName": "Politics",
        "webPublicationDate": "2016-05-27T11:32:33Z",
        "webTitle": "Vote Leave launches £50m football prediction competition",
        "webUrl": "https://www.theguardian.com/politics/2016/may/27/vote-leave-launches-50m-football-prediction-competition-euro-2016",
        "apiUrl": "https://content.guardianapis.com/politics/2016/may/27/vote-leave-launches-50m-football-prediction-competition-euro-2016",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/dec/26/football-league-your-thoughts-derby-fulham",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-12-26T17:35:23Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/dec/26/football-league-your-thoughts-derby-fulham",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/dec/26/football-league-your-thoughts-derby-fulham",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/dec/19/football-league-your-thoughts-derby-ipswich-rotherham",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-12-19T18:58:19Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/dec/19/football-league-your-thoughts-derby-ipswich-rotherham",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/dec/19/football-league-your-thoughts-derby-ipswich-rotherham",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/dec/12/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-12-12T19:51:03Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/dec/12/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/dec/12/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/10/football-transfer-rumours-arsenal-and-everton-move-for-wilfried-bony",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-10T07:29:35Z",
        "webTitle": "Football transfer rumours: Arsenal and Everton move for Wilfried Bony?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/10/football-transfer-rumours-arsenal-and-everton-move-for-wilfried-bony",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/10/football-transfer-rumours-arsenal-and-everton-move-for-wilfried-bony",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/12/bt-sport-score-afternoon-viewers-soccer-saturday",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-12T15:56:23Z",
        "webTitle": "BT Sport make their play for Saturday afternoon football viewers",
        "webUrl": "https://www.theguardian.com/football/2016/aug/12/bt-sport-score-afternoon-viewers-soccer-saturday",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/12/bt-sport-score-afternoon-viewers-soccer-saturday",
        "isHosted": false
      },
      {
        "id": "sport/2016/aug/09/usa-colombia-rio-2016-olympics-hope-solo",
        "type": "article",
        "sectionId": "sport",
        "sectionName": "Sport",
        "webPublicationDate": "2016-08-10T00:32:01Z",
        "webTitle": "Women's football: Hope Solo errors help Colombia draw with USA",
        "webUrl": "https://www.theguardian.com/sport/2016/aug/09/usa-colombia-rio-2016-olympics-hope-solo",
        "apiUrl": "https://content.guardianapis.com/sport/2016/aug/09/usa-colombia-rio-2016-olympics-hope-solo",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/09/football-transfer-rumours-chelsea-beat-arsenal-to-mauro-icardi",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-09T07:31:08Z",
        "webTitle": "Football transfer rumours: Chelsea beat Arsenal to Mauro Icardi?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/09/football-transfer-rumours-chelsea-beat-arsenal-to-mauro-icardi",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/09/football-transfer-rumours-chelsea-beat-arsenal-to-mauro-icardi",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/10/football-teams-who-had-cigarette-brands-as-a-shirt-sponsor",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-10T09:15:33Z",
        "webTitle": "Football teams who had cigarette brands as a shirt sponsor | The Knowledge",
        "webUrl": "https://www.theguardian.com/football/2016/aug/10/football-teams-who-had-cigarette-brands-as-a-shirt-sponsor",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/10/football-teams-who-had-cigarette-brands-as-a-shirt-sponsor",
        "isHosted": false
      },
      {
        "id": "football/2016/may/02/football-transfer-rumours-robert-lewandowski-arsenal-william-carvalho-leicester-city",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-05-02T08:22:17Z",
        "webTitle": "Football transfer rumours: Robert Lewandowski to Arsenal?",
        "webUrl": "https://www.theguardian.com/football/2016/may/02/football-transfer-rumours-robert-lewandowski-arsenal-william-carvalho-leicester-city",
        "apiUrl": "https://content.guardianapis.com/football/2016/may/02/football-transfer-rumours-robert-lewandowski-arsenal-william-carvalho-leicester-city",
        "isHosted": false
      },
      {
        "id": "technology/2016/aug/05/british-olympic-team-hashtag-nebraska-cornhuskers-twitter",
        "type": "article",
        "sectionId": "technology",
        "sectionName": "Technology",
        "webPublicationDate": "2016-08-05T20:39:57Z",
        "webTitle": "Clashtag: British Olympians 'steal' #GBR from Nebraska Huskers football fans",
        "webUrl": "https://www.theguardian.com/technology/2016/aug/05/british-olympic-team-hashtag-nebraska-cornhuskers-twitter",
        "apiUrl": "https://content.guardianapis.com/technology/2016/aug/05/british-olympic-team-hashtag-nebraska-cornhuskers-twitter",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/04/football-league-preview-championship-league-one-two",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-04T13:00:21Z",
        "webTitle": "Reasons for optimism: Football League fans preview the season",
        "webUrl": "https://www.theguardian.com/football/2016/aug/04/football-league-preview-championship-league-one-two",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/04/football-league-preview-championship-league-one-two",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/03/the-20-greatest-female-football-players-soccer",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-03T08:00:42Z",
        "webTitle": "The 20 greatest female football players of all time",
        "webUrl": "https://www.theguardian.com/football/2016/aug/03/the-20-greatest-female-football-players-soccer",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/03/the-20-greatest-female-football-players-soccer",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/03/football-transfer-rumours-liverpool-jonas-hector-koln",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-03T08:00:03Z",
        "webTitle": "Football transfer rumours: Liverpool to sign Jonas Hector from Köln?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/03/football-transfer-rumours-liverpool-jonas-hector-koln",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/03/football-transfer-rumours-liverpool-jonas-hector-koln",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/02/football-transfer-rumours-west-ham-mario-gomez",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-02T08:06:31Z",
        "webTitle": "Football transfer rumours: West Ham set to sign Mario Gómez?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/02/football-transfer-rumours-west-ham-mario-gomez",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/02/football-transfer-rumours-west-ham-mario-gomez",
        "isHosted": false
      },
      {
        "id": "football/blog/2016/may/06/the-joy-of-six-football-chants",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-05-06T10:00:22Z",
        "webTitle": "The Joy of Six: football chants",
        "webUrl": "https://www.theguardian.com/football/blog/2016/may/06/the-joy-of-six-football-chants",
        "apiUrl": "https://content.guardianapis.com/football/blog/2016/may/06/the-joy-of-six-football-chants",
        "isHosted": false
      },
      {
        "id": "uk-news/davehillblog/2016/aug/13/london-football-income-regeneration-and-muddy-memory-lanes",
        "type": "article",
        "sectionId": "uk-news",
        "sectionName": "UK news",
        "webPublicationDate": "2016-08-13T08:58:54Z",
        "webTitle": "London football: income, regeneration and muddy memory lanes",
        "webUrl": "https://www.theguardian.com/uk-news/davehillblog/2016/aug/13/london-football-income-regeneration-and-muddy-memory-lanes",
        "apiUrl": "https://content.guardianapis.com/uk-news/davehillblog/2016/aug/13/london-football-income-regeneration-and-muddy-memory-lanes",
        "isHosted": false
      },
      {
        "id": "education/2016/aug/13/uk-universities-mad-for-football-studies",
        "type": "article",
        "sectionId": "education",
        "sectionName": "Education",
        "webPublicationDate": "2016-08-13T20:00:16Z",
        "webTitle": "Football focus: sports degrees are now a serious student option",
        "webUrl": "https://www.theguardian.com/education/2016/aug/13/uk-universities-mad-for-football-studies",
        "apiUrl": "https://content.guardianapis.com/education/2016/aug/13/uk-universities-mad-for-football-studies",
        "isHosted": false
      },
      {
        "id": "football/live/2016/aug/09/olympic-womens-football-colombia-usa-live",
        "type": "liveblog",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-09T23:54:59Z",
        "webTitle": "Olympic women's football: Colombia 2-2 USA – as it happened",
        "webUrl": "https://www.theguardian.com/football/live/2016/aug/09/olympic-womens-football-colombia-usa-live",
        "apiUrl": "https://content.guardianapis.com/football/live/2016/aug/09/olympic-womens-football-colombia-usa-live",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/01/football-transfer-rumours-jonny-evans-and-mauro-icardi-to-arsenal",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-01T07:25:52Z",
        "webTitle": "Football transfer rumours: Jonny Evans and Mauro Icardi to Arsenal?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/01/football-transfer-rumours-jonny-evans-and-mauro-icardi-to-arsenal",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/01/football-transfer-rumours-jonny-evans-and-mauro-icardi-to-arsenal",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/29/football-transfer-rumours-arsenal-shkodran-mustafi",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-29T08:11:00Z",
        "webTitle": "Football transfer rumours: Arsenal to sign Shkodran Mustafi?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/29/football-transfer-rumours-arsenal-shkodran-mustafi",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/29/football-transfer-rumours-arsenal-shkodran-mustafi",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/05/football-transfer-rumours-real-madrid-to-swoop-for-david-alaba",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-05T07:52:19Z",
        "webTitle": "Football transfer rumours: Real Madrid to move for David Alaba?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/05/football-transfer-rumours-real-madrid-to-swoop-for-david-alaba",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/05/football-transfer-rumours-real-madrid-to-swoop-for-david-alaba",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/26/football-transfer-rumours-kalidou-koulibaly-marko-arnautovic-everton",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-26T07:54:37Z",
        "webTitle": "Football transfer rumours: Kalidou Koulibaly and Marko Arnautovic to Everton?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/26/football-transfer-rumours-kalidou-koulibaly-marko-arnautovic-everton",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/26/football-transfer-rumours-kalidou-koulibaly-marko-arnautovic-everton",
        "isHosted": false
      },
      {
        "id": "media/2016/aug/03/times-football-hillsborough-joe-tony-barrett",
        "type": "article",
        "sectionId": "media",
        "sectionName": "Media",
        "webPublicationDate": "2016-08-03T11:47:40Z",
        "webTitle": "Times football writer who quit over Hillsborough coverage joins Joe.co.uk",
        "webUrl": "https://www.theguardian.com/media/2016/aug/03/times-football-hillsborough-joe-tony-barrett",
        "apiUrl": "https://content.guardianapis.com/media/2016/aug/03/times-football-hillsborough-joe-tony-barrett",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/03/football-transfer-records-broken-by-teams-outside-the-top-division",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-03T09:00:43Z",
        "webTitle": "Football transfer records broken by teams outside the top division | The Knowledge",
        "webUrl": "https://www.theguardian.com/football/2016/aug/03/football-transfer-records-broken-by-teams-outside-the-top-division",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/03/football-transfer-records-broken-by-teams-outside-the-top-division",
        "isHosted": false
      },
      {
        "id": "football/2016/apr/20/football-transfer-rumours-francesco-totti-to-leicester",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-20T08:05:14Z",
        "webTitle": "Football transfer rumours: Francesco Totti to Leicester?",
        "webUrl": "https://www.theguardian.com/football/2016/apr/20/football-transfer-rumours-francesco-totti-to-leicester",
        "apiUrl": "https://content.guardianapis.com/football/2016/apr/20/football-transfer-rumours-francesco-totti-to-leicester",
        "isHosted": false
      },
      {
        "id": "football/2016/aug/02/football-quiz-how-well-do-you-know-your-agents",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-08-02T09:00:13Z",
        "webTitle": "Football quiz: how well do you know your agents?",
        "webUrl": "https://www.theguardian.com/football/2016/aug/02/football-quiz-how-well-do-you-know-your-agents",
        "apiUrl": "https://content.guardianapis.com/football/2016/aug/02/football-quiz-how-well-do-you-know-your-agents",
        "isHosted": false
      },
      {
        "id": "football/2015/nov/28/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-11-28T20:10:59Z",
        "webTitle": "Football League: your thoughts | Les Roopanarine",
        "webUrl": "https://www.theguardian.com/football/2015/nov/28/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/2015/nov/28/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "world/2016/jul/26/israeli-police-raids-target-beitar-jerusalem-fc-football-hooligans",
        "type": "article",
        "sectionId": "world",
        "sectionName": "World news",
        "webPublicationDate": "2016-07-26T11:05:38Z",
        "webTitle": "Israeli police raids target Beitar Jerusalem football hooligans",
        "webUrl": "https://www.theguardian.com/world/2016/jul/26/israeli-police-raids-target-beitar-jerusalem-fc-football-hooligans",
        "apiUrl": "https://content.guardianapis.com/world/2016/jul/26/israeli-police-raids-target-beitar-jerusalem-fc-football-hooligans",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/nov/21/football-league-your-thoughts-blog-brentford-nottingham-forest",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-11-21T19:03:18Z",
        "webTitle": "Football League: your thoughts | Rob Bleaney",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/nov/21/football-league-your-thoughts-blog-brentford-nottingham-forest",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/nov/21/football-league-your-thoughts-blog-brentford-nottingham-forest",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/22/football-transfer-rumours-edinson-cavani-psg-chelsea",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-22T07:50:28Z",
        "webTitle": "Football transfer rumours: Edinson Cavani to leave PSG for Chelsea?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/22/football-transfer-rumours-edinson-cavani-psg-chelsea",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/22/football-transfer-rumours-edinson-cavani-psg-chelsea",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/21/football-transfer-rumours-romelu-lukaku-going-back-to-chelsea",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-21T08:26:18Z",
        "webTitle": "Football transfer rumours: Romelu Lukaku going back to Chelsea?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/21/football-transfer-rumours-romelu-lukaku-going-back-to-chelsea",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/21/football-transfer-rumours-romelu-lukaku-going-back-to-chelsea",
        "isHosted": false
      },
      {
        "id": "football/blog/2016/apr/15/the-joy-of-six-football-player-managers",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-15T09:21:47Z",
        "webTitle": "The Joy of Six: football player-managers",
        "webUrl": "https://www.theguardian.com/football/blog/2016/apr/15/the-joy-of-six-football-player-managers",
        "apiUrl": "https://content.guardianapis.com/football/blog/2016/apr/15/the-joy-of-six-football-player-managers",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/19/football-quiz-name-the-player-from-their-transfer-history",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-19T13:14:59Z",
        "webTitle": "Football quiz: name the player from their transfer history",
        "webUrl": "https://www.theguardian.com/football/2016/jul/19/football-quiz-name-the-player-from-their-transfer-history",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/19/football-quiz-name-the-player-from-their-transfer-history",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/19/football-transfer-rumours-newcastles-georginio-wijnaldum-to-liverpool",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-19T08:17:06Z",
        "webTitle": "Football transfer rumours: Newcastle's Georginio Wijnaldum to Liverpool?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/19/football-transfer-rumours-newcastles-georginio-wijnaldum-to-liverpool",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/19/football-transfer-rumours-newcastles-georginio-wijnaldum-to-liverpool",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/27/the-least-impressive-winners-of-a-major-football-tournament-statistically",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-27T09:00:38Z",
        "webTitle": "The least impressive winners of a major football tournament (statistically) | The Knowledge",
        "webUrl": "https://www.theguardian.com/football/2016/jul/27/the-least-impressive-winners-of-a-major-football-tournament-statistically",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/27/the-least-impressive-winners-of-a-major-football-tournament-statistically",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/20/football-transfer-rumours-mauro-icardi-to-arsenal-from-inter",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-20T08:28:22Z",
        "webTitle": "Football transfer rumours: Mauro Icardi to Arsenal from Inter?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/20/football-transfer-rumours-mauro-icardi-to-arsenal-from-inter",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/20/football-transfer-rumours-mauro-icardi-to-arsenal-from-inter",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/25/football-transfer-rumours-juventus-javier-mascherano-barcelona",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-25T07:21:04Z",
        "webTitle": "Football transfer rumours: Juventus to sign Javier Mascherano from Barcelona?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/25/football-transfer-rumours-juventus-javier-mascherano-barcelona",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/25/football-transfer-rumours-juventus-javier-mascherano-barcelona",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/16/football-league-investigates-nottingham-forest-takeover-bid-banned-tycoon",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-16T09:00:07Z",
        "webTitle": "Football League investigates Nottingham Forest takeover bid by banned tycoon",
        "webUrl": "https://www.theguardian.com/football/2016/jul/16/football-league-investigates-nottingham-forest-takeover-bid-banned-tycoon",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/16/football-league-investigates-nottingham-forest-takeover-bid-banned-tycoon",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/13/football-transfer-rumours-cesc-fabregas-to-manchester-united",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-13T07:51:11Z",
        "webTitle": "Football transfer rumours: Cesc Fàbregas to Manchester United?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/13/football-transfer-rumours-cesc-fabregas-to-manchester-united",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/13/football-transfer-rumours-cesc-fabregas-to-manchester-united",
        "isHosted": false
      },
      {
        "id": "sport/2016/jul/12/premier-league-rivalries-unravelled-a-history-of-english-football-derbies",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-12T00:21:37Z",
        "webTitle": "Premier League rivalries unravelled: a history of English football derbies | Nick Miller",
        "webUrl": "https://www.theguardian.com/sport/2016/jul/12/premier-league-rivalries-unravelled-a-history-of-english-football-derbies",
        "apiUrl": "https://content.guardianapis.com/sport/2016/jul/12/premier-league-rivalries-unravelled-a-history-of-english-football-derbies",
        "isHosted": false
      },
      {
        "id": "football/football-league-blog/2015/nov/14/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-11-14T18:17:53Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/football-league-blog/2015/nov/14/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/football-league-blog/2015/nov/14/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/18/football-transfer-rumours-joe-allen-manchester-united-liverpool",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-18T07:06:45Z",
        "webTitle": "Football transfer rumours: Joe Allen to Manchester United from Liverpool?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/18/football-transfer-rumours-joe-allen-manchester-united-liverpool",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/18/football-transfer-rumours-joe-allen-manchester-united-liverpool",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/08/pep-guardiola-manchester-city-culture-english-football",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-08T21:30:33Z",
        "webTitle": "Pep Guardiola says he cannot change everything about English football",
        "webUrl": "https://www.theguardian.com/football/2016/jul/08/pep-guardiola-manchester-city-culture-english-football",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/08/pep-guardiola-manchester-city-culture-english-football",
        "isHosted": false
      },
      {
        "id": "small-business-network/kia-fleet-partner-zone/2016/jul/06/football-fever-and-the-possibilities-for-your-business",
        "type": "article",
        "sectionId": "small-business-network/kia-fleet-partner-zone",
        "sectionName": "KIA Fleet partner zone",
        "webPublicationDate": "2016-07-06T11:47:43Z",
        "webTitle": "Football fever and the possibilities for your business",
        "webUrl": "https://www.theguardian.com/small-business-network/kia-fleet-partner-zone/2016/jul/06/football-fever-and-the-possibilities-for-your-business",
        "apiUrl": "https://content.guardianapis.com/small-business-network/kia-fleet-partner-zone/2016/jul/06/football-fever-and-the-possibilities-for-your-business",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/08/wales-football-team-touch-down-heroes-welcome-cardiff-airport-euro-2016",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-08T14:33:30Z",
        "webTitle": "Wales football team touch down to heroes' welcome in Cardiff",
        "webUrl": "https://www.theguardian.com/football/2016/jul/08/wales-football-team-touch-down-heroes-welcome-cardiff-airport-euro-2016",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/08/wales-football-team-touch-down-heroes-welcome-cardiff-airport-euro-2016",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/14/football-transfer-rumours-julian-draxler-gonzalo-higuain-arsenal",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-14T07:43:46Z",
        "webTitle": "Football transfer rumours: Julian Draxler or Gonzalo Higuaín to Arsenal?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/14/football-transfer-rumours-julian-draxler-gonzalo-higuain-arsenal",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/14/football-transfer-rumours-julian-draxler-gonzalo-higuain-arsenal",
        "isHosted": false
      },
      {
        "id": "football/2015/oct/31/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-10-31T17:58:41Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/2015/oct/31/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/2015/oct/31/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/2016/jan/11/football-quiz-ballon-dor-winners",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-11T13:08:31Z",
        "webTitle": "Football quiz: Ballon d'Or winners",
        "webUrl": "https://www.theguardian.com/football/2016/jan/11/football-quiz-ballon-dor-winners",
        "apiUrl": "https://content.guardianapis.com/football/2016/jan/11/football-quiz-ballon-dor-winners",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/06/football-transfer-rumours-manchester-city-chasing-leonardo-bonucci",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-06T07:51:03Z",
        "webTitle": "Football transfer rumours: Manchester City chasing Leonardo Bonucci?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/06/football-transfer-rumours-manchester-city-chasing-leonardo-bonucci",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/06/football-transfer-rumours-manchester-city-chasing-leonardo-bonucci",
        "isHosted": false
      },
      {
        "id": "football/blog/2016/jul/12/euro-2016-death-possession-football",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-12T08:43:57Z",
        "webTitle": "The Question: was Euro 2016 the death of possession football? | Jonathan Wilson",
        "webUrl": "https://www.theguardian.com/football/blog/2016/jul/12/euro-2016-death-possession-football",
        "apiUrl": "https://content.guardianapis.com/football/blog/2016/jul/12/euro-2016-death-possession-football",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/05/football-transfer-rumours-arsenal-to-sign-romelu-lukaku",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-05T08:17:11Z",
        "webTitle": "Football transfer rumours: Arsenal to sign Romelu Lukaku?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/05/football-transfer-rumours-arsenal-to-sign-romelu-lukaku",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/05/football-transfer-rumours-arsenal-to-sign-romelu-lukaku",
        "isHosted": false
      },
      {
        "id": "football/live/2016/apr/30/premier-league-football-league-clockwatch-live",
        "type": "liveblog",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-04-30T16:24:43Z",
        "webTitle": "Premier League, Football League and European football: clockwatch – as it happened",
        "webUrl": "https://www.theguardian.com/football/live/2016/apr/30/premier-league-football-league-clockwatch-live",
        "apiUrl": "https://content.guardianapis.com/football/live/2016/apr/30/premier-league-football-league-clockwatch-live",
        "isHosted": false
      },
      {
        "id": "football/2016/jan/07/football-quiz-identify-the-referee",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-01-07T11:22:29Z",
        "webTitle": "Football quiz: identify the referee",
        "webUrl": "https://www.theguardian.com/football/2016/jan/07/football-quiz-identify-the-referee",
        "apiUrl": "https://content.guardianapis.com/football/2016/jan/07/football-quiz-identify-the-referee",
        "isHosted": false
      },
      {
        "id": "politics/2016/jun/28/when-english-football-mirrors-its-politics-all-too-well",
        "type": "article",
        "sectionId": "politics",
        "sectionName": "Politics",
        "webPublicationDate": "2016-06-28T18:22:49Z",
        "webTitle": "When English football mirrors its politics all too well | Letters",
        "webUrl": "https://www.theguardian.com/politics/2016/jun/28/when-english-football-mirrors-its-politics-all-too-well",
        "apiUrl": "https://content.guardianapis.com/politics/2016/jun/28/when-english-football-mirrors-its-politics-all-too-well",
        "isHosted": false
      },
      {
        "id": "football/2016/mar/24/johan-cruyff-obituary",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-03-24T14:07:16Z",
        "webTitle": "Johan Cruyff obituary: Europe’s first football superstar",
        "webUrl": "https://www.theguardian.com/football/2016/mar/24/johan-cruyff-obituary",
        "apiUrl": "https://content.guardianapis.com/football/2016/mar/24/johan-cruyff-obituary",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/07/football-transfer-rumours-chelsea-hold-talks-with-lionel-messi",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-07T08:04:55Z",
        "webTitle": "Football transfer rumours: Chelsea hold talks with Lionel Messi?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/07/football-transfer-rumours-chelsea-hold-talks-with-lionel-messi",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/07/football-transfer-rumours-chelsea-hold-talks-with-lionel-messi",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/28/football-transfer-rumours-hector-bellerin-to-barcelona",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-28T08:37:31Z",
        "webTitle": "Football transfer rumours: Arsenal's Héctor Bellerín to Barcelona?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/28/football-transfer-rumours-hector-bellerin-to-barcelona",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/28/football-transfer-rumours-hector-bellerin-to-barcelona",
        "isHosted": false
      },
      {
        "id": "sport/2016/jun/30/smarter-football-concussion-crisis-nfl",
        "type": "article",
        "sectionId": "sport",
        "sectionName": "Sport",
        "webPublicationDate": "2016-06-30T10:00:00Z",
        "webTitle": "History shows 'smarter' football is no match for concussion",
        "webUrl": "https://www.theguardian.com/sport/2016/jun/30/smarter-football-concussion-crisis-nfl",
        "apiUrl": "https://content.guardianapis.com/sport/2016/jun/30/smarter-football-concussion-crisis-nfl",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/30/football-transfer-rumours-leicesters-ngolo-kante-to-real-madrid",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-30T07:35:32Z",
        "webTitle": "Football transfer rumours: Leicester's N'Golo Kanté to Real Madrid?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/30/football-transfer-rumours-leicesters-ngolo-kante-to-real-madrid",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/30/football-transfer-rumours-leicesters-ngolo-kante-to-real-madrid",
        "isHosted": false
      },
      {
        "id": "commentisfree/2016/jun/28/england-football-team-we-deserve",
        "type": "article",
        "sectionId": "commentisfree",
        "sectionName": "Opinion",
        "webPublicationDate": "2016-06-28T15:43:09Z",
        "webTitle": "We get the England football team we deserve | David Conn",
        "webUrl": "https://www.theguardian.com/commentisfree/2016/jun/28/england-football-team-we-deserve",
        "apiUrl": "https://content.guardianapis.com/commentisfree/2016/jun/28/england-football-team-we-deserve",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/04/football-transfer-rumours-real-madrid-to-sign-spurs-hugo-lloris",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-04T07:42:38Z",
        "webTitle": "Football transfer rumours: Real Madrid to sign Spurs' Hugo Lloris?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/04/football-transfer-rumours-real-madrid-to-sign-spurs-hugo-lloris",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/04/football-transfer-rumours-real-madrid-to-sign-spurs-hugo-lloris",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/23/jamie-vardy-england-contract-football-association-unimpressed",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-23T21:30:07Z",
        "webTitle": "Jamie Vardy’s contract news leaves Football Association unimpressed",
        "webUrl": "https://www.theguardian.com/football/2016/jun/23/jamie-vardy-england-contract-football-association-unimpressed",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/23/jamie-vardy-england-contract-football-association-unimpressed",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/23/football-transfer-rumours-arsenals-aaron-ramsey-to-manchester-united",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-23T08:11:21Z",
        "webTitle": "Football transfer rumours: Arsenal's Aaron Ramsey to Manchester United?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/23/football-transfer-rumours-arsenals-aaron-ramsey-to-manchester-united",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/23/football-transfer-rumours-arsenals-aaron-ramsey-to-manchester-united",
        "isHosted": false
      },
      {
        "id": "football/2016/jul/01/football-transfer-rumours-newcastle-moussa-sissoko-liverpool",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-07-01T07:34:26Z",
        "webTitle": "Football transfer rumours: Newcastle’s Moussa Sissoko to Liverpool?",
        "webUrl": "https://www.theguardian.com/football/2016/jul/01/football-transfer-rumours-newcastle-moussa-sissoko-liverpool",
        "apiUrl": "https://content.guardianapis.com/football/2016/jul/01/football-transfer-rumours-newcastle-moussa-sissoko-liverpool",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/24/football-transfer-rumours-arsenal-alexis-sanchez-juventus",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-24T08:08:51Z",
        "webTitle": "Football transfer rumours: Arsenal’s Alexis Sánchez to Juventus?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/24/football-transfer-rumours-arsenal-alexis-sanchez-juventus",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/24/football-transfer-rumours-arsenal-alexis-sanchez-juventus",
        "isHosted": false
      },
      {
        "id": "fashion/2016/jun/23/white-hot-a-history-of-bleached-hair-in-football",
        "type": "article",
        "sectionId": "fashion",
        "sectionName": "Fashion",
        "webPublicationDate": "2016-06-23T07:03:04Z",
        "webTitle": "White hot: a history of bleached hair in football",
        "webUrl": "https://www.theguardian.com/fashion/2016/jun/23/white-hot-a-history-of-bleached-hair-in-football",
        "apiUrl": "https://content.guardianapis.com/fashion/2016/jun/23/white-hot-a-history-of-bleached-hair-in-football",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/29/football-transfer-rumours-james-rodriguez-manchester-city-chelsea",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-29T08:30:51Z",
        "webTitle": "Football transfer rumours: James Rodríguez to Manchester City or Chelsea?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/29/football-transfer-rumours-james-rodriguez-manchester-city-chelsea",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/29/football-transfer-rumours-james-rodriguez-manchester-city-chelsea",
        "isHosted": false
      },
      {
        "id": "football/2015/oct/24/football-league-your-thoughts",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2015-10-24T17:37:44Z",
        "webTitle": "Football League: your thoughts",
        "webUrl": "https://www.theguardian.com/football/2015/oct/24/football-league-your-thoughts",
        "apiUrl": "https://content.guardianapis.com/football/2015/oct/24/football-league-your-thoughts",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/21/football-transfer-rumours-paul-pogba-real-madrid",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-21T07:26:24Z",
        "webTitle": "Football transfer rumours: Paul Pogba to Real Madrid?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/21/football-transfer-rumours-paul-pogba-real-madrid",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/21/football-transfer-rumours-paul-pogba-real-madrid",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/27/football-transfer-rumours-lyon-alexandre-lacazette-to-arsenal",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-27T07:56:59Z",
        "webTitle": "Football transfer rumours: Lyon's Alexandre Lacazette to Arsenal?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/27/football-transfer-rumours-lyon-alexandre-lacazette-to-arsenal",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/27/football-transfer-rumours-lyon-alexandre-lacazette-to-arsenal",
        "isHosted": false
      },
      {
        "id": "football/2016/jun/20/football-transfer-rumours-leonardo-bonucci-to-manchester-united",
        "type": "article",
        "sectionId": "football",
        "sectionName": "Football",
        "webPublicationDate": "2016-06-20T08:22:47Z",
        "webTitle": "Football transfer rumours: Leonardo Bonucci to Manchester United?",
        "webUrl": "https://www.theguardian.com/football/2016/jun/20/football-transfer-rumours-leonardo-bonucci-to-manchester-united",
        "apiUrl": "https://content.guardianapis.com/football/2016/jun/20/football-transfer-rumours-leonardo-bonucci-to-manchester-united",
        "isHosted": false
      },
      {
        "id": "commentisfree/2016/jun/16/the-guardian-view-on-russian-football-hooligans-politics-at-play",
        "type": "article",
        "sectionId": "commentisfree",
        "sectionName": "Opinion",
        "webPublicationDate": "2016-06-16T18:57:34Z",
        "webTitle": "The Guardian view on Russian football hooligans: politics at play | Editorial",
        "webUrl": "https://www.theguardian.com/commentisfree/2016/jun/16/the-guardian-view-on-russian-football-hooligans-politics-at-play",
        "apiUrl": "https://content.guardianapis.com/commentisfree/2016/jun/16/the-guardian-view-on-russian-football-hooligans-politics-at-play",
        "isHosted": false
      },
      {
        "id": "technology/2016/jun/16/facebook-messenger-hidden-football-gameeuro-2016",
        "type": "article",
        "sectionId": "technology",
        "sectionName": "Technology",
        "webPublicationDate": "2016-06-16T10:19:50Z",
        "webTitle": "Facebook Messenger's hidden football game is strangely addictive",
        "webUrl": "https://www.theguardian.com/technology/2016/jun/16/facebook-messenger-hidden-football-gameeuro-2016",
        "apiUrl": "https://content.guardianapis.com/technology/2016/jun/16/facebook-messenger-hidden-football-gameeuro-2016",
        "isHosted": false
      }
    ]
  }
}

  res.send(data);
});

