'use strict';
var router = require('express').Router();
module.exports = router;

// Yahoo Stocks dummy data

router.get('/', function (req, res, next) {
  let data = {
    "query": {
      "count": 2,
      "created": "2016-08-13T21:17:22Z",
      "lang": "en-US",
      "results": {
        "quote": [
          {
            "symbol": "GOOG",
            "Ask": "784.85",
            "AverageDailyVolume": "1615410",
            "Bid": "782.90",
            "AskRealtime": null,
            "BidRealtime": null,
            "BookValue": "186.20",
            "Change_PercentChange": "-1.63 - -0.21%",
            "Change": "-1.63",
            "Commission": null,
            "Currency": "USD",
            "ChangeRealtime": null,
            "AfterHoursChangeRealtime": null,
            "DividendShare": null,
            "LastTradeDate": "8/12/2016",
            "TradeDate": null,
            "EarningsShare": "25.81",
            "ErrorIndicationreturnedforsymbolchangedinvalid": null,
            "EPSEstimateCurrentYear": "34.31",
            "EPSEstimateNextYear": "40.76",
            "EPSEstimateNextQuarter": "9.68",
            "DaysLow": "780.40",
            "DaysHigh": "783.40",
            "YearLow": "565.05",
            "YearHigh": "789.87",
            "HoldingsGainPercent": null,
            "AnnualizedGain": null,
            "HoldingsGain": null,
            "HoldingsGainPercentRealtime": null,
            "HoldingsGainRealtime": null,
            "MoreInfo": null,
            "OrderBookRealtime": null,
            "MarketCapitalization": "538.29B",
            "MarketCapRealtime": null,
            "EBITDA": "26.90B",
            "ChangeFromYearLow": "218.17",
            "PercentChangeFromYearLow": "+38.61%",
            "LastTradeRealtimeWithTime": null,
            "ChangePercentRealtime": null,
            "ChangeFromYearHigh": "-6.65",
            "PercebtChangeFromYearHigh": "-0.84%",
            "LastTradeWithTime": "4:00pm - <b>783.22</b>",
            "LastTradePriceOnly": "783.22",
            "HighLimit": null,
            "LowLimit": null,
            "DaysRange": "780.40 - 783.40",
            "DaysRangeRealtime": null,
            "FiftydayMovingAverage": "734.40",
            "TwoHundreddayMovingAverage": "722.94",
            "ChangeFromTwoHundreddayMovingAverage": "60.28",
            "PercentChangeFromTwoHundreddayMovingAverage": "+8.34%",
            "ChangeFromFiftydayMovingAverage": "48.82",
            "PercentChangeFromFiftydayMovingAverage": "+6.65%",
            "Name": "Alphabet Inc.",
            "Notes": null,
            "Open": "781.50",
            "PreviousClose": "784.85",
            "PricePaid": null,
            "ChangeinPercent": "-0.21%",
            "PriceSales": "6.60",
            "PriceBook": "4.22",
            "ExDividendDate": null,
            "PERatio": "30.35",
            "DividendPayDate": null,
            "PERatioRealtime": null,
            "PEGRatio": "1.24",
            "PriceEPSEstimateCurrentYear": "22.83",
            "PriceEPSEstimateNextYear": "19.22",
            "Symbol": "GOOG",
            "SharesOwned": null,
            "ShortRatio": "1.18",
            "LastTradeTime": "4:00pm",
            "TickerTrend": null,
            "OneyrTargetPrice": "917.55",
            "Volume": "740498",
            "HoldingsValue": null,
            "HoldingsValueRealtime": null,
            "YearRange": "565.05 - 789.87",
            "DaysValueChange": null,
            "DaysValueChangeRealtime": null,
            "StockExchange": "NMS",
            "DividendYield": null,
            "PercentChange": "-0.21%"
          },
          {
            "symbol": "AAPL",
            "Ask": "108.14",
            "AverageDailyVolume": "35363900",
            "Bid": "108.10",
            "AskRealtime": null,
            "BidRealtime": null,
            "BookValue": "23.46",
            "Change_PercentChange": "+0.25 - +0.23%",
            "Change": "+0.25",
            "Commission": null,
            "Currency": "USD",
            "ChangeRealtime": null,
            "AfterHoursChangeRealtime": null,
            "DividendShare": "2.28",
            "LastTradeDate": "8/12/2016",
            "TradeDate": null,
            "EarningsShare": "8.58",
            "ErrorIndicationreturnedforsymbolchangedinvalid": null,
            "EPSEstimateCurrentYear": "8.26",
            "EPSEstimateNextYear": "8.91",
            "EPSEstimateNextQuarter": "3.11",
            "DaysLow": "107.78",
            "DaysHigh": "108.44",
            "YearLow": "89.47",
            "YearHigh": "123.82",
            "HoldingsGainPercent": null,
            "AnnualizedGain": null,
            "HoldingsGain": null,
            "HoldingsGainPercentRealtime": null,
            "HoldingsGainRealtime": null,
            "MoreInfo": null,
            "OrderBookRealtime": null,
            "MarketCapitalization": "582.92B",
            "MarketCapRealtime": null,
            "EBITDA": "73.96B",
            "ChangeFromYearLow": "18.71",
            "PercentChangeFromYearLow": "+20.91%",
            "LastTradeRealtimeWithTime": null,
            "ChangePercentRealtime": null,
            "ChangeFromYearHigh": "-15.64",
            "PercebtChangeFromYearHigh": "-12.63%",
            "LastTradeWithTime": "4:00pm - <b>108.18</b>",
            "LastTradePriceOnly": "108.18",
            "HighLimit": null,
            "LowLimit": null,
            "DaysRange": "107.78 - 108.44",
            "DaysRangeRealtime": null,
            "FiftydayMovingAverage": "100.32",
            "TwoHundreddayMovingAverage": "99.98",
            "ChangeFromTwoHundreddayMovingAverage": "8.20",
            "PercentChangeFromTwoHundreddayMovingAverage": "+8.20%",
            "ChangeFromFiftydayMovingAverage": "7.86",
            "PercentChangeFromFiftydayMovingAverage": "+7.84%",
            "Name": "Apple Inc.",
            "Notes": null,
            "Open": "107.78",
            "PreviousClose": "107.93",
            "PricePaid": null,
            "ChangeinPercent": "+0.23%",
            "PriceSales": "2.64",
            "PriceBook": "4.60",
            "ExDividendDate": "8/4/2016",
            "PERatio": "12.61",
            "DividendPayDate": "5/12/2016",
            "PERatioRealtime": null,
            "PEGRatio": "1.66",
            "PriceEPSEstimateCurrentYear": "13.10",
            "PriceEPSEstimateNextYear": "12.14",
            "Symbol": "AAPL",
            "SharesOwned": null,
            "ShortRatio": "1.27",
            "LastTradeTime": "4:00pm",
            "TickerTrend": null,
            "OneyrTargetPrice": "124.11",
            "Volume": "18660434",
            "HoldingsValue": null,
            "HoldingsValueRealtime": null,
            "YearRange": "89.47 - 123.82",
            "DaysValueChange": null,
            "DaysValueChangeRealtime": null,
            "StockExchange": "NMS",
            "DividendYield": "2.11",
            "PercentChange": "+0.23%"
          }
        ]
      }
    }
  }
  res.send(data);
});

